/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.freedesktop.DBus.Properties.xml -p mediaplayer2propertiesinterface -c MediaPlayer2PropertiesInterface
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mediaplayer2propertiesinterface.h"

/*
 * Implementation of interface class MediaPlayer2PropertiesInterface
 */

MediaPlayer2PropertiesInterface::MediaPlayer2PropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MediaPlayer2PropertiesInterface::~MediaPlayer2PropertiesInterface()
{
}

